### ISSUE TITLE
Typo on clock_correction computation

### ISSUE THREAD

**Issue by Emilien942702** [commaai/laika#1]
Hi,

I think you have made a typo [here](https://github.com/commaai/laika/blob/f8bde3cc1b3bd442922bf45f40ca8b28251588b3/laika/ephemeris.py#L184).

This is located in `class GPSEphemeris(Ephemeris):`, `def get_sat_info(self, time):`
You do : 
```
...
tdiff = time - eph['toe']  # Time of clock
clock_err = eph['af0'] + tdiff * (eph['af1'] + tdiff * eph['af2'])
clock_rate_err = eph['af1'] + 2 * tdiff * eph['af2']
# Orbit propagation
tdiff = time - eph['toe']  # Time of ephemeris (might be different from time of clock)
```

Shouldn't it be : 
```
...
tdiff = time - eph['toc']  # Time of clock
...
``` 
instead ?

It would make more sense (to use Toc instead of Toe to compute the clock_error) and would fit with the comments you have made.

Thanks,
Emilien

**Comment by HaraldSchafer** [comment]
Yes you are right, thank you for pointing that out. I fixed it.
