### ISSUE TITLE
`url_bases` vs `url_base` mixup in `downloader.py`

### ISSUE THREAD

**Issue by haydenshively** [commaai/laika#141]
The function [`download_and_cache_file_return_first_success`](https://github.com/commaai/laika/blob/6fadabd86043ee19e06c6ed59aa4e688c14fa8e4/laika/downloader.py#L243) accepts an array of `url_bases` and hands them off to [`download_and_cache_file`](https://github.com/commaai/laika/blob/6fadabd86043ee19e06c6ed59aa4e688c14fa8e4/laika/downloader.py#LL256C5-L256C28), which expects just a _single_ `url_base`. This causes the url concatenation to fail in `download_file`.

To fix this, I'd suggest something like this in `download_and_cache_file_return_first_success`:
```python
if not os.path.isfile(filepath) or overwrite:
  for url_base in url_bases: # <-- critical that we iterate over these somehow
    try:
      data_zipped = download_file(url_base, folder_path, filename_zipped)
      break
    except (DownloadFailed, pycurl.error, socket.timeout):
      data_zipped = None

  if data_zipped is None:
    unix_time = time.time()
    os.makedirs(folder_path_abs, exist_ok=True)
    with atomic_write(filepath_attempt, mode='w', overwrite=True) as wf:
      wf.write(str(unix_time))
    raise DownloadFailed(f"Could not download {folder_path + filename_zipped} from {url_bases} ")
```

I can put up a PR if you want; just not sure what the contribution guidelines are. Thanks!

**Comment by HaraldSchafer** [comment]
The retryable decorator deals with this, but I agree it's very confusing to read
