### ISSUE TITLE
Running with live data

### ISSUE THREAD

**Issue by AlexKaravaev** [commaai/laika#15]
Hi!

I think my question may be a little be bit stupid, but still I am wondering if I can use this library for live data? 

I have ublox F9P and kind of raspberry pi, and I want to get better results with gps data, however all examples are dealing with binary files. If I want to use it with device, I should just read from serial, instead of file, is it that straightforward? Or I should consider other approach?

Thanks in advance.

**Comment by HaraldSchafer** [comment]
Yes you can definitely use this live. You have to get the F9P to send raw data over serial, then parse it and format it for use in laika. We use laika live with ublox modules as well.

Here is our ublox interface code that might provide good inspiration
https://github.com/commaai/openpilot/blob/master/selfdrive/locationd/test/ubloxd.py
