### ISSUE TITLE
Kalman Filter Notebook doesn't work

### ISSUE THREAD

**Issue by JST2018** [commaai/laika#19]
Hi there,

I'm just getting started to understand, how things done with this library, but especially the KF and DGPS things are interesting to me. Unfortunately the Notebook for KF isn't working, because of the missing laika_repo. You can also see this in the notebook on github in the 8th cell.

Best regards,
J.

**Comment by HaraldSchafer** [comment]
Hey, 
Yeah that seems to be broken. Unfortunately I don't have time to fix it at the moment. If you're motivated to get it to work, you should be able to get the gnss kalman from here https://github.com/commaai/openpilot/tree/master/selfdrive/locationd/kalman and get it to work. rwschubert has done that in the PR, which you can also check out.

If you find an easy fix that isn't too much code, I'd be happy to merge it.

Let me know if you have more questions

**Comment by gijskoning** [comment]
The KF notebook seems to work fine. Closing
