### ISSUE TITLE
KeyError when read BEIDOU or QZNSS satellite info

### ISSUE THREAD

**Issue by fivitti** [commaai/laika#21]
When I execute code:
```python
dog = AstroDog(valid_const=["QZNSS"])
time = datetime.datetime(2020, 5, 1)
sat_info = dog.get_sat_info("J01", time)
```
I got:
```
File "/home/lv/Projects/magisterka/src/sources/laika.py", line 26, in source
    sat_info = dog.get_sat_info(sat_prn, time)
  File "/home/lv/Projects/magisterka/src/.env/src/laika/laika/astro_dog.py", line 233, in get_sat_info
    eph = self.get_orbit(prn, time)
  File "/home/lv/Projects/magisterka/src/.env/src/laika/laika/astro_dog.py", line 95, in get_orbit
    self.get_orbit_data(time)
  File "/home/lv/Projects/magisterka/src/.env/src/laika/laika/astro_dog.py", line 174, in get_orbit_data
    self.add_ephem(ephem, self.orbits)
  File "/home/lv/Projects/magisterka/src/.env/src/laika/laika/astro_dog.py", line 143, in add_ephem
    ephems[prn].append(new_ephem)
KeyError: 'J07'
```

After execute this code from ```get_orbit_data``` from ```astro_dog.py```:
```python
file_paths_sp3_ru = download_orbits_russia(time, cache_dir=self.cache_dir)
ephems_sp3_ru = parse_sp3_orbits(file_paths_sp3_ru, self.valid_const)
```
then it returns items with prns: ```['J01', 'J02', 'J03', 'J07']```.
Laika's code expects that prn numbers are continuous and throws KeyError when it try to add "J07" ephemeris.

Another situation is when you try to fetch BeiDou satellite info. Laika has hardcoded BeiDou size equals 14, but [now we have 48 satellites](https://www.glonass-iac.ru/en/BEIDOU/) in constellation. 
When I fetch orbits using Laika then I get prns: ```[
C01, C03, C05, C06, C08, C09, C10, C11, C12, C13, C14, C16, C19, C20, C21, C22, C23, C24, C25, C26, C27, C28, C29, C30, C32, C33, C34, C35, C36, C37]```.

As temporary solution you can increase constellation sizes. But I think that it should be refactored. Now Laika crashes after launch next satellite. If you want I can help you with that.

**Comment by HaraldSchafer** [comment]
Yes, I agree that it would be best to remove this hardcoding.

I think my logic at the time was that by hardcoding the expected satellites we can raise warnings when no info is found for a satellite, that we expect to exist. Perhaps this is unnecessary.

Are you suggesting we don't fill in the PRNs in astro dog here: 
https://github.com/commaai/laika/blob/55e0796b25479f1676fbaa40b4893202b95e66ae/laika/astro_dog.py#L45
And instead just add the PRNs to astrodog on the fly as they are found in the data files? 

Alternatively we could keep the hardcoding as an "expected constellation size", and just add the prn if one is found that isn't already in astrodog, so there are no more crashes.

Either way, would be happy to merge a pull request that fixes this cleanly and is tested. Keep in mind current tests only test GPS and GLONASS. If you expect laika to work with other constellations, adding tests for those would be appreciated.

Thanks for your input!

**Comment by fivitti** [comment]
> Are you suggesting we don't fill in the PRNs in astro dog here:
   And instead just add the PRNs to astrodog on the fly as they are found in the data files?

Yes, I think that AstroDog may to use defaultdict instead of standard dictionaries and avoid pre-fill for each satellite.

> Alternatively we could keep the hardcoding as an "expected constellation size", and just add the 
   prn if one is found that isn't already in astrodog, so there are no more crashes.

It may be a bad pattern. The code may still break after launch new satellite. And we aren't sure that the numbering will be continuous.

> Either way, would be happy to merge a pull request that fixes this cleanly and is tested. Keep in 
   mind current tests only test GPS and GLONASS. If you expect laika to work with other 
   constellations, adding tests for those would be appreciated.

Ok, sure. Clean code and unit tests. All constellations are very important for me. I don't know Laika well yet, but it seems to me that this shouldn't be a big change.

**Comment by HaraldSchafer** [comment]
Yeah shouldn't be a big change. Looking forward to it!
