### ISSUE TITLE
Quiet ignoring Galileo, Beidou when pull_orbit is False

### ISSUE THREAD

**Issue by fivitti** [commaai/laika#26]
If pull_orbit is set to False then Laika fetch sat info only for GPS and GLONASS. But user doesn't have any information that it fails for other constellations. Maybe Laika should throw exception (NotImplemented) when user creates AstroDog instance with pull_orbit=False and not supported constellations?

**Comment by HaraldSchafer** [comment]
Yes, that's a good idea
