### ISSUE TITLE
GPS Prediction

### ISSUE THREAD

**Issue by jrdutra** [commaai/laika#34]
Hello, can I predict GPS satellites visibility with this software??

**Comment by fivitti** [comment]
Hi!
Yes, you can. You can use Laika to calculate satellite positions in ECEF. If you know the receive position you can calculate the elevation of each satellite. If elevation is greater then zero (or specific angle) then satellite is visible.

If you need more accurate visibility analyse then you need DEM (digital elevation model). You can combine it with azimuth/elevation of satellite from Laika and calculate the covering by obstacles.

**Comment by jrdutra** [comment]
Sorry for ask this, but how can I calculate the Elevation of the satelite using laika? I didn't found an exemple here in the repository.

**Comment by fivitti** [comment]
Look at [Walkthrough](https://github.com/commaai/laika/blob/master/examples/Walkthrough.ipynb).

In 14 cell you have an example of calulcations.

```python
from laika.lib.coordinates import LocalCoord

receiver_position = [-2702584.60036925, -4325039.45362552,  3817393.16034817]
sat_positions = ... # List of tuples with ECEF satellite corrdinates fetched by Laika

converter = LocalCoord.from_ecef(receiver_position)
sat_positions_ned = converter.ecef2ned(sat_positions)
azimuths_radians = np.arctan2(sat_positions_ned[:,0], sat_positions_ned[:,1])
elevation_radians = np.arctan2(-sat_positions_ned[:,2], np.linalg.norm(sat_positions_ned[:,:2],axis=1))
```

-------------

You can also use function [get_el_az](https://github.com/commaai/laika/blob/a27fc6a839a7e886d77459527e7adc5f424a1d01/laika/helpers.py#L81) to do it. This function contains the same calculations as above Walkthrough.

**Comment by jrdutra** [comment]
Wow..cool! I'm developing an android app that shows the flyght conditions for drones. And one of the parameters to determine if it's good to fly is the satellites visible amount. I don't want to use a 3rd API to provide the Sats informations. I want to build my won API. If I use Laika, I will give the credits of this repository inside the APP.

So, I have two doubts:

**First:**

```python
receiver_position = [-2702584.60036925, -4325039.45362552,  3817393.16034817]
```
**-2702584.60036925 = x
-4325039.45362552 = y
3817393.16034817 = z

So, I will have to convert my latitude, longitude, and altitude to ECEF and submit to this functiion...
Is it right?

**Second:**

`sat_positions = ... # List of tuples with ECEF satellite corrdinates fetched by Laika`

Laika can fetch the GPS ECEF cordinates?

**Comment by jrdutra** [comment]
By the way, here is the screen that I'm drawing for the app:
![print](https://raw.githubusercontent.com/jrdutra/droneenv/main/other_files/Screenshot_1604075682.png)

**Comment by jrdutra** [comment]
Hi!!! Thanks a lot!!!! 
As soon as I have some times I will study more and run the Walkthrought.
I think I will be able to implment this API for my APP. First I will use an existent api, just to release the APP on playstore, and latter I will try to implement my won api using Laika giving the credits in the App.
