### ISSUE TITLE
Fusion of Doppler and pseudorange measurements integration using the EKF 

### ISSUE THREAD

**Issue by weisongwen** [commaai/laika#37]
Thanks for sharing this good package. Currently, can this package support the integration of the pseudorange and Doppler measurements using the EKF?

Best,
Weisong.

**Comment by HaraldSchafer** [comment]
Yes it does, but this library does not include an EKF.

**Comment by weisongwen** [comment]
Hi @HaraldSchafer  Thanks for your reply. you mean this package supports the integration of the pseudorange and Doppler measurements but the integration is not based on EKF? could you please kindly point out where I can get access to the demo?

Best,
Weisong,

**Comment by HaraldSchafer** [comment]
Laika is a gnss processing library. Raw GNSS observables (like pseudoranges and doppler shifts) need to be processed and corrected before they can be used. Laika does all this. The processed measurements can then be used in an optimizer (like an EKF) to estimate position and velocity. Laika does no include an EKF. We have a different library for that. https://github.com/commaai/rednose

Here is an implementation of a rednose EKF we use with laika to get precise GNSS results. https://github.com/commaai/openpilot/blob/master/selfdrive/locationd/models/gnss_kf.py, unfortunately we have little documentation outside of what is provided in rednose and in the laika examples.

**Comment by weisongwen** [comment]
Hi @HaraldSchafer ,

Thanks for your kind reply. Well noted with thanks. 

Best,
Weisong,
