### ISSUE TITLE
DGPS documentation

### ISSUE THREAD

**Issue by lital103** [commaai/laika#5]
Hi, I've heard a lot of recommendation about your library but I'm having a bit of a hard time operating it.  I'm trying to do a coordinate correction experiment on the DGPS method. Can you please give me some examples of a simple use of the DGPS functionality?
Thanks.

**Comment by HaraldSchafer** [comment]
Hello, 
I unfortunately did not document any examples of dgps. Although it did work well when I worked on it, it should be easy to use.

In the walkthrough:
https://github.com/commaai/laika/blob/master/examples/Walkthrough.ipynb
In cell 3 Astrodog is used to get delays for a satellite. If you initialize with:
`AstroDog(dgps=True)`
Then it will calculate the delay using DGPS stations. Note that this only works in the USA.
Lemme know if you have more questions or bug reports.
