### ISSUE TITLE
consult about the performance of NEO M8T with laika

### ISSUE THREAD

**Issue by ideafold** [commaai/laika#63]
Thanks for the great work!

In this issue, https://github.com/commaai/laika/issues/4, anuragxel recommend M8T.
does any one have test neo m8t with Laika lib?
how about the performance? 
Beside M8T, is there any other good and cheap device from ublox(should be compatible with Laika) ？
Thanks

**Comment by HaraldSchafer** [comment]
Laika can process any GNSS observation data.

We use ublox modules, all the tests were done with ublox M8.
